services:
  registry:
    image: registry
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.registry.rule: Host(`registry.${DOMAIN}`)
      traefik.http.services.registry.loadbalancer.server.port: 5000
    networks:
      traefik:
networks:
  traefik:
    external: true
